---
title: "Welcome to My Portfolio!"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index2.html'))})
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<div class="green"> [MIT License
Copyright (c) 2020 Oscar Cardec](docs/"LICENSE.txt")
</div>

<br/>

### Projects

- #### [Cardiotocograms Interpretation and Classification with RStudio CTREE](CTREE/CTREE_RMarkdown.html)

- #### [National Security Strategy Text Analysis with NLTK and Tableau Visualizations](text_analysis/README.html)

<br/>

### Reports

- #### [Classification of Aircraft's Lateral Deviation](reports/ClassificationACFTLateralDeviation.pdf)
  
- #### [Landsat Multispectral Scanner Image's Classification with Kmeans Clustering](reports/Unsupervised%20Learning%20w%20Kmeans.pdf)

- #### [Breast Cancer Dataset Classification with RStudio NeuralNet](reports/Neural%20Networks%20in%20R.pdf)

- #### [Vehicles Valuation with Multilinear Regression in R](reports/Multiple%20Linear%20Regression.pdf)

- #### [Association Rules for Credit Approvals with Apriori](reports/Association%20w%20Apriori.pdf)

- #### [Logistic Regresion and Default of Credit Card Payments](reports/Logistic%20Regression.pdf) 

