---
title: "Welcome to Oscar's Portfolio!"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
[MIT License
Copyright (c) 2020 Oscar Cardec](file:///Users/ocardec/Documents/GitHub/ocardec.github.io/font_page/LICENSE)

<br/>

### Projects

- [Cardiotocograms Interpretation and Classification with RStudio CTREE](file:///Users/ocardec/Documents/GitHub/ocardec.github.io/CTREE/CTREE_RMarkdown.html)

- [National Security Strategy Text Analysis with NLTK and Tableau Visualizations](file:///Users/ocardec/Documents/GitHub/ocardec.github.io/text_analysis/README.html)

<br/>

### Reports

- [Landsat Multispectral Scanner Image's Classification with Kmeans Clustering](file:///Users/ocardec/Documents/GitHub//ocardec.github.io/reports/Unsupervised%20Learning%20w%20Kmeans.pdf)

- [Breast Cancer Dataset Classification with RStudio NeuralNet](file:///Users/ocardec/Documents/GitHub//ocardec.github.io/reports/Neural%20Networks%20in%20R.pdf)

- [Vehicles Valuation with Multilinear Regression in R](file:///Users/ocardec/Documents/GitHub//ocardec.github.io/reports/Multiple%20Linear%20Regression.pdf)

- [Association Rules for Credit Approvals with Apriori](file:///Users/ocardec/Documents/GitHub//ocardec.github.io/reports/Association%20w%20Apriori.pdf)

- [Logistic Regresion and Default of Credit Card Payments](file:///Users/ocardec/Documents/GitHub//ocardec.github.io/reports/Logistic%20Regression.pdf)



